# Generated by Django 5.2.10 on 2026-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
