# Generated by Django 5.2.10 on 2026-01-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_page_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='text_content',
        ),
    ]
